version: '3'
services: 
    api:
        container_name: api-indicacao-amigo
        build: .
        ports:
            - 8006:80
        volumes: 
            - ./:/app
        depends_on: 
            - db
    db:
        image: postgres:13.3
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=indicacao_amigo
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes: 
            - ./postgres-data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
                